GET http://localhost:5132/api/book

###
GET http://localhost:5132/api/book/4

###
DELETE http://localhost:5132/api/book/3



###
POST http://localhost:5132/api/book
Content-Type : application/json

{
    "title": "Les dents de la mers",
    "author": "Kemuza Leon",
    "releaseDate": "2021-05-11"
}

###
PUT http://localhost:5132/api/book/4
Content-Type : application/json

{
    "title": "La mer des GRAND ",
    "author": "Percy",
    "releaseDate": "2021-05-11"
}
    