# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Library.Api/Library.Api.csproj", "Library.Api/"]
RUN dotnet restore "Library.Api/Library.Api.csproj"

COPY . .
WORKDIR "/src/Library.Api"
RUN dotnet build "Library.Api.csproj" -c Release -o /app/build

# Publish stage
FROM build AS publish
RUN dotnet publish "Library.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
EXPOSE 5132
ENV ASPNETCORE_URLS=http://+:5132

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Library.Api.dll"]
