version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: library-api
    ports:
      - "5132:5132"
    networks:
      - library-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: library-client
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - library-network

volumes:
  library-data:

networks:
  library-network:
    driver: bridge
